- hosts: localhost
  vars:
    nodejs_version: "18.x"
    nodejs_npm_global_packages:
      - yarn
      - eslint
      - typescript
      - typescript-language-server
      - ts-node
    go_version: "1.18.3"
    go_checksum: "956f8507b302ab0bb747613695cdae10af99bbd39a90cae522b7c0302cc27245"
    packer_version: "1.8.2"

  pre_tasks:
    - name: Update apt
      become: true
      apt:
        update_cache: true
        state: present
  roles:
    - core
    - role: geerlingguy.docker
      become: yes
    - role: geerlingguy.nodejs
      become: yes
    - name: geerlingguy.go
      become: yes
    - geerlingguy.packer
    - geerlingguy.helm
  post_tasks:
    - include_tasks: tasks/cloud-setup.yml
