- hosts: localhost
  pre_tasks:
  - name: Update dnf
    become: true
    dnf:
      update_cache: true
      state: present
  tasks:
    - include_tasks: tasks/core-setup.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/cloud-setup.yml
    - include_tasks: tasks/languages-setup.yml
    - include_tasks: tasks/nvim-setup.yml
