- hosts: localhost
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        update_cache: true
        state: present
  tasks:
    - include_tasks: tasks/core-setup.yml
    - include_tasks: tasks/brave.yml
    - include_tasks: tasks/nvim-setup.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/node-setup.yml
    - include_tasks: tasks/npm-packages.yml
    - include_tasks: tasks/cloud-setup.yml
    - include_tasks: tasks/dotfiles.yml
