---
- name: Install launchers (steam, lutris, heroic launcher)
  community.general.flatpak:
    name: [com.valvesoftware.Steam, com.heroicgameslauncher.hgl]
    state: present

- name: Install Lutris
  community.general.flatpak:
    name: net.lutris.Lutris
    state: present
    remote: flathub-beta

- name: Install Discord
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present
