- name: Install some prerequisites
  become: yes
  apt:
    name: [apt-transport-https, curl]
    state: present

- name: Add Brave repos
  get_url:
    url: https://brave-browser-apt-beta.s3.brave.com/brave-browser-beta-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-beta-archive-keyring.gpg
  tags:
    - essentials
    - software
    - browser

- name: Install essential programs
  become: yes
  apt:
    name: [brave, zsh, neovim, tmux, flatpak, git, pip, i3, fzf]
  tags:
    - essentials
    - software

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - essentials
    - software

- name: Install eseential flatpaks
  community.general.flatpak:
    name:
      [
        com.obsproject.Studio,
        com.discordapp.Discord,
        org.keepassxc.KeePassXC,
        org.gimp.GIMP,
      ]
    state: present
  tags:
    - essentials
    - software
