- name: Install some prerequisites
  become: yes
  apt:
    name: [apt-transport-https, curl]
    state: present

- name: Install essential programs
  become: yes
  apt:
    name:
      [
        zsh,
        tmux,
        flatpak,
        git,
        pip,
        i3,
        fzf,
        golang,
        python3-pip,
        dconf-editor,
        moreutils,
        x11-xserver-utils,
      ]
  tags:
    - essentials
    - software

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - essentials
    - software

- name: Install eseential flatpaks
  community.general.flatpak:
    name:
      [
        com.obsproject.Studio,
        com.discordapp.Discord,
        org.keepassxc.KeePassXC,
        org.gimp.GIMP,
        com.slack.Slack,
        org.videolan.VLC,
        io.neovim.nvim,
      ]
    state: present
  tags:
    - essentials
    - software
