---
- name: Make sure that zsh is installed and updated
  apt:
    name: zsh
    state: latest

- name: Check that .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_stats

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: zsh
  when: oh_my_stats.stat.exists == False
  become_user: mszczepanski

- name: Make ZSH default shell
  become: yes
  user:
    name: mszczepanski
    shell: /bin/zsh

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
