- include_tasks: repos.yml
- name: Install essential programs
  become: yes
  apt:
    name:
      [
        apt-transport-https,
        curl,
        wget,
        zsh,
        tmux,
        flatpak,
        gnome-software-plugin-flatpak,
        git,
        pip,
        fzf,
        python3-pip,
        moreutils,
        build-essential,
        cmake,
        pkg-config,
        libpthread-stubs0-dev,
        lua5.1,
        unzip,
        libtool,
        libtool-bin,
        gettext,
        gnome-shell-extensions,
        brave-browser,
        awscli,
        google-cloud-cli,
        kubectl,
        keepassxc,
        fonts-powerline,
        gnome-tweaks,
        lazygit
      ]
  tags:
    - essentials
    - software

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - essentials
    - software

- name: Add Flathub Beta
  community.general.flatpak_remote:
    name: flathub-beta
    state: present
    flatpakrepo_url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo

- name: Install eseential flatpaks
  community.general.flatpak:
    name:
      [
        com.obsproject.Studio,
        org.gimp.GIMP,
        com.slack.Slack,
        org.videolan.VLC,
      ]
    state: present
  tags:
    - essentials
    - software

- name: Extract k9s to /bin
  become: yes
  ansible.builtin.unarchive:
    src: https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    include: [k9s]

- include_tasks: git.yml
- include_tasks: dotfiles.yml
- include_tasks: zsh.yml
- include_tasks: neovim.yml
