- name: Install essential programs
  become: yes
  apt:
    name:
      [
        apt-transport-https,
        curl,
        wget,
        zsh,
        tmux,
        flatpak,
        gnome-software-plugin-flatpak,
        git,
        pip,
        fzf,
        python3-pip,
        moreutils,
        build-essential,
        cmake,
        pkg-config,
        libpthread-stubs0-dev,
        lua5.1,
        unzip,
        libtool,
        libtool-bin,
        gettext,
        gnome-shell-extensions,
      ]
  tags:
    - essentials
    - software

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - essentials
    - software

- name: Install eseential flatpaks
  community.general.flatpak:
    name:
      [
        com.obsproject.Studio,
        com.discordapp.Discord,
        org.keepassxc.KeePassXC,
        org.gimp.GIMP,
        com.slack.Slack,
        org.videolan.VLC,
      ]
    state: present
  tags:
    - essentials
    - software

- include_tasks: brave.yml
- include_tasks: git.yml
- include_tasks: dotfiles.yml
- include_tasks: zsh.yml
- include_tasks: neovim.yml
